// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sun Sep 15 14:08:23 2019

lab2 lab2_inst
(
	.we(we_sig) ,	// input  we_sig
	.arst(arst_sig) ,	// input  arst_sig
	.data(data_sig) ,	// input [31:0] data_sig
	.clk(clk_sig) ,	// input  clk_sig
	.RW(RW_sig) ,	// input [4:0] RW_sig
	.RA(RA_sig) ,	// input [4:0] RA_sig
	.RB(RB_sig) ,	// input [4:0] RB_sig
	.OUTA(OUTA_sig) ,	// output [31:0] OUTA_sig
	.OUTB(OUTB_sig) 	// output [31:0] OUTB_sig
);

